eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
server:
  port: 10002
spring:
  application:
    name: PriceRatingService
  rabbitmq:
    host: 192.168.182.132
    port: 5672
    username: guest
    password: guest